### ISSUE TITLE
Minor issue with too short on hex-encoded output

### ISSUE THREAD

**Issue by svenvds** [curzon01/mysql_PBKDF2#1]
Unsure if this intended, but the hex-encoded output is only half the length of the requested key-length.

At the end of the PBKDF2 the hex-encoded key is chopped to the requested key-length, but unless I'm mistaken the binary key needs to be chopped to the requested key-length and then hex-encoded.

so instead of:
   RETURN LOWER(CONVERT(LEFT(HEX(output), key_length) USING latin1));
The following should be used.
   RETURN LOWER(CONVERT(HEX(LEFT(output, key_length)) USING latin1));

regards,

**Comment by curzon01** [comment]
The output with original code is:

`SELECT system.PBKDF2('SHA256', 'password', 'salt', 2, 16, false);`
`0x61653464306339356166366234366433`

These are 16 byte and correct.

`RETURN LOWER(CONVERT(HEX(LEFT(output, key_length)) USING latin1))`
delivers double long result:

`SELECT system.PBKDF2('SHA256', 'password', 'salt', 2, 16, false);`
`0x6165346430633935616636623436643332643061646666393238663036646430`

The expected keylength is 16 byte, the result of your change are 32 bytes.
